[deploy]
startCommand = "/bin/bash -c \"/bin/ttyd -p 7681 -c $USERNAME:$PASSWORD /bin/bash\""
numReplicas = 1

[deploy.resources]
memoryMb = 1024
vcpus = 2

[[volumes]]
mountPath = "/root"
name = "kali-data"
